## Imports

In [117]:
import numpy as np
import pandas as pd

## Dataset

In [118]:
datos_pinguinos = pd.read_csv('./penguins_cleaned.csv',header=0)
# data.columns = ['explicitly','rename','headers']

datos_pinguinos

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0       Adelie  Torgersen            39.1           18.7                181   
1       Adelie  Torgersen            39.5           17.4                186   
2       Adelie  Torgersen            40.3           18.0                195   
3       Adelie  Torgersen            36.7           19.3                193   
4       Adelie  Torgersen            39.3           20.6                190   
..         ...        ...             ...            ...                ...   
328  Chinstrap      Dream            55.8           19.8                207   
329  Chinstrap      Dream            43.5           18.1                202   
330  Chinstrap      Dream            49.6           18.2                193   
331  Chinstrap      Dream            50.8           19.0                210   
332  Chinstrap      Dream            50.2           18.7                198   

     body_mass_g     sex  
0           3750    male  
1           3800  female  
2           3250  female  
3           3450  female  
4           3650    male  
..           ...     ...  
328         4000    male  
329         3400  female  
330         3775    male  
331         4100    male  
332         3775  female  

[333 rows x 7 columns]

In [119]:
df = datos_pinguinos.copy()
target = 'species'
encode = ['island', 'sex']

for col in encode:
    dummy = pd.get_dummies(df[col], prefix=col)    
    df = pd.concat([df, dummy], axis=1)
    del df[col]
    
target_mapping = {'Adelie':0, 'Gentoo':1, 'Chinstrap':2}

In [120]:
def target_encoding(val):
    return target_mapping[val]

In [121]:
df['species'] = df['species'].apply(target_encoding)

In [122]:
# Datos de ingreso excluyen la especie
input_df = df.drop('species', axis=1)

### Características de data en dataset

In [123]:
desc_df = datos_pinguinos.filter(['island','bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g','sex'], axis=1)

desc_df.describe(include='all')

island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
count      333      333.000000     333.000000         333.000000   333.000000   
unique       3             NaN            NaN                NaN          NaN   
top     Biscoe             NaN            NaN                NaN          NaN   
freq       163             NaN            NaN                NaN          NaN   
mean       NaN       43.992793      17.164865         200.966967  4207.057057   
std        NaN        5.468668       1.969235          14.015765   805.215802   
min        NaN       32.100000      13.100000         172.000000  2700.000000   
25%        NaN       39.500000      15.600000         190.000000  3550.000000   
50%        NaN       44.500000      17.300000         197.000000  4050.000000   
75%        NaN       48.600000      18.700000         213.000000  4775.000000   
max        NaN       59.600000      21.500000         231.000000  6300.000000   

         sex  
count    333  
unique     2  
top     male  
freq     168  
mean     NaN  
std      NaN  
min      NaN  
25%      NaN  
50%      NaN  
75%      NaN  
max      NaN

### Normalizar y codificar

In [124]:
normalized_df = input_df.copy()
normalized_df = (normalized_df-normalized_df.mean())/normalized_df.std()
# Mostrar dataframe
# normalized_df

In [125]:
n_input_df = normalized_df.copy()

key_list = list(input_df['island_Biscoe'])
key_list2 = list(input_df['island_Dream'])
key_list3 = list(input_df['island_Torgersen'])
key_list4 = list(input_df['sex_female'])
key_list5 = list(input_df['sex_male'])

dict_lookup = dict(zip(input_df['island_Biscoe'], input_df['island_Biscoe']))
dict_lookup2 = dict(zip(input_df['island_Dream'], input_df['island_Dream']))
dict_lookup3 = dict(zip(input_df['island_Torgersen'], input_df['island_Torgersen']))
dict_lookup4 = dict(zip(input_df['sex_female'], input_df['sex_female']))
dict_lookup4 = dict(zip(input_df['sex_male'], input_df['sex_male']))

In [126]:
n_input_df['island_Biscoe'] = [dict_lookup[item] for item in key_list]
n_input_df['island_Dream'] = [dict_lookup[item] for item in key_list2]
n_input_df['island_Torgersen'] = [dict_lookup[item] for item in key_list3]
n_input_df['sex_female'] = [dict_lookup[item] for item in key_list4]
n_input_df['sex_male'] = [dict_lookup[item] for item in key_list5]

# Mostar dataframe
#n_input_df

In [127]:
# Definir X e Y
X = n_input_df
Y = df.filter(['species'], axis=1)

X

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0         -0.894695       0.779559          -1.424608    -0.567621   
1         -0.821552       0.119404          -1.067867    -0.505525   
2         -0.675264       0.424091          -0.425733    -1.188572   
3         -1.333559       1.084246          -0.568429    -0.940192   
4         -0.858123       1.744400          -0.782474    -0.691811   
..              ...            ...                ...          ...   
328        2.159064       1.338151           0.430446    -0.257145   
329       -0.090112       0.474872           0.073705    -1.002287   
330        1.025333       0.525653          -0.568429    -0.536573   
331        1.244765       0.931902           0.644491    -0.132954   
332        1.135049       0.779559          -0.211688    -0.536573   

     island_Biscoe  island_Dream  island_Torgersen  sex_female  sex_male  
0                0             0                 1           0         1  
1                0             0                 1           1         0  
2                0             0                 1           1         0  
3                0             0                 1           1         0  
4                0             0                 1           0         1  
..             ...           ...               ...         ...       ...  
328              0             1                 0           0         1  
329              0             1                 0           1         0  
330              0             1                 0           0         1  
331              0             1                 0           0         1  
332              0             1                 0           1         0  

[333 rows x 9 columns]

In [128]:
Y

species
0          0
1          0
2          0
3          0
4          0
..       ...
328        2
329        2
330        2
331        2
332        2

[333 rows x 1 columns]

### De dataframe a matrices Numpy

## Red Multicapa de referencia

In [129]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

In [136]:
#Entradas 
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
#Salidas reales
expected_output =np.array([[0],[1],[1],[0]])

#epocas
epochs=5000

#factor de aprendizaje
lr=0.25

#Neuronas de capa entrada a coger // capa oculta //Capa salida
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons=2,2,1

#Pesos aleatorios para la capa oculta
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))

#Pesos aleatorios para umbral bias de la capa oculta
#(una entrada mas que se le considera a la neurona en la capa oculta)
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))

#Pesos para la capa salida
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))

#Pesos aleatorios para umbral bias de la capa salida
output_bias = np.random.uniform(size=(1,outputLayerNeurons))

In [138]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [135]:
expected_output

array([[0],
       [1],
       [1],
       [0]])

In [131]:
for _ in range(epochs):
    #Forward Propagation
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = sigmoid(output_layer_activation)

    #Backpropagation
    error = expected_output - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    #Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer) * lr

In [132]:
print("Pesos finales: ")
print(hidden_weights)
print("bias finales: ")
print(hidden_bias)
print("Pesos finales capa de salida: ")
print(output_weights)
print("bias finales capa de salida: ")
print(output_bias)

print("\n Predicción : ")
print(predicted_output)

Pesos finales: 
[[3.52245505 8.57881543]
 [3.52299869 8.58089603]]
bias finales: 
[[-5.25570895 -5.57418412]]
Pesos finales capa de salida: 
[[-10.54822274]
 [  9.02536017]]
bias finales capa de salida: 
[[-3.45452923]]

 Predicción : 
[[0.03002924]
 [0.9723657 ]
 [0.97236269]
 [0.03023924]]
