## Imports

In [594]:
import numpy as np
import pandas as pd

## Dataset

In [595]:
datos_pinguinos = pd.read_csv('./penguins_cleaned.csv',header=0)
# data.columns = ['explicitly','rename','headers']

datos_pinguinos

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0       Adelie  Torgersen            39.1           18.7                181   
1       Adelie  Torgersen            39.5           17.4                186   
2       Adelie  Torgersen            40.3           18.0                195   
3       Adelie  Torgersen            36.7           19.3                193   
4       Adelie  Torgersen            39.3           20.6                190   
..         ...        ...             ...            ...                ...   
328  Chinstrap      Dream            55.8           19.8                207   
329  Chinstrap      Dream            43.5           18.1                202   
330  Chinstrap      Dream            49.6           18.2                193   
331  Chinstrap      Dream            50.8           19.0                210   
332  Chinstrap      Dream            50.2           18.7                198   

     body_mass_g     sex  
0           3750    male  
1           3800  female  
2           3250  female  
3           3450  female  
4           3650    male  
..           ...     ...  
328         4000    male  
329         3400  female  
330         3775    male  
331         4100    male  
332         3775  female  

[333 rows x 7 columns]

In [596]:
df = datos_pinguinos.copy()
encode = ['island', 'sex', 'species']

for col in encode:
    dummy = pd.get_dummies(df[col], prefix=col)
    df = pd.concat([df, dummy], axis=1)
    del df[col]

In [597]:
# target = 'species'
# target_mapping = {'Adelie':0, 'Gentoo':1, 'Chinstrap':2}
# def target_encoding(val):
#     return target_mapping[val]

# df['species'] = df['species'].apply(target_encoding)

In [598]:
# Dataframe codificado
df

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0              39.1           18.7                181         3750   
1              39.5           17.4                186         3800   
2              40.3           18.0                195         3250   
3              36.7           19.3                193         3450   
4              39.3           20.6                190         3650   
..              ...            ...                ...          ...   
328            55.8           19.8                207         4000   
329            43.5           18.1                202         3400   
330            49.6           18.2                193         3775   
331            50.8           19.0                210         4100   
332            50.2           18.7                198         3775   

     island_Biscoe  island_Dream  island_Torgersen  sex_female  sex_male  \
0                0             0                 1           0         1   
1                0             0                 1           1         0   
2                0             0                 1           1         0   
3                0             0                 1           1         0   
4                0             0                 1           0         1   
..             ...           ...               ...         ...       ...   
328              0             1                 0           0         1   
329              0             1                 0           1         0   
330              0             1                 0           0         1   
331              0             1                 0           0         1   
332              0             1                 0           1         0   

     species_Adelie  species_Chinstrap  species_Gentoo  
0                 1                  0               0  
1                 1                  0               0  
2                 1                  0               0  
3                 1                  0               0  
4                 1                  0               0  
..              ...                ...             ...  
328               0                  1               0  
329               0                  1               0  
330               0                  1               0  
331               0                  1               0  
332               0                  1               0  

[333 rows x 12 columns]

In [599]:
df.loc[147,:]

bill_length_mm         50.0
bill_depth_mm          16.3
flipper_length_mm     230.0
body_mass_g          5700.0
island_Biscoe           1.0
island_Dream            0.0
island_Torgersen        0.0
sex_female              0.0
sex_male                1.0
species_Adelie          0.0
species_Chinstrap       0.0
species_Gentoo          1.0
Name: 147, dtype: float64

In [600]:
# Datos de ingreso excluyen la especie, y la salida las contiene
input_df = df.drop(['species_Adelie','species_Chinstrap','species_Gentoo'], axis=1)
output_df = df.filter(['species_Adelie','species_Chinstrap','species_Gentoo'], axis=1)

### Características de data en dataset

In [601]:
desc_df = datos_pinguinos.filter(['island','bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g','sex'], axis=1)

desc_df.describe(include='all')

island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
count      333      333.000000     333.000000         333.000000   333.000000   
unique       3             NaN            NaN                NaN          NaN   
top     Biscoe             NaN            NaN                NaN          NaN   
freq       163             NaN            NaN                NaN          NaN   
mean       NaN       43.992793      17.164865         200.966967  4207.057057   
std        NaN        5.468668       1.969235          14.015765   805.215802   
min        NaN       32.100000      13.100000         172.000000  2700.000000   
25%        NaN       39.500000      15.600000         190.000000  3550.000000   
50%        NaN       44.500000      17.300000         197.000000  4050.000000   
75%        NaN       48.600000      18.700000         213.000000  4775.000000   
max        NaN       59.600000      21.500000         231.000000  6300.000000   

         sex  
count    333  
unique     2  
top     male  
freq     168  
mean     NaN  
std      NaN  
min      NaN  
25%      NaN  
50%      NaN  
75%      NaN  
max      NaN

### Normalizar y codificar

In [602]:
normalized_df = input_df.copy()
normalized_df = (normalized_df-normalized_df.mean())/normalized_df.std()
# Mostrar dataframe
# normalized_df

In [603]:
n_input_df = normalized_df.copy()

key_list = list(input_df['island_Biscoe'])
key_list2 = list(input_df['island_Dream'])
key_list3 = list(input_df['island_Torgersen'])
key_list4 = list(input_df['sex_female'])
key_list5 = list(input_df['sex_male'])

dict_lookup = dict(zip(input_df['island_Biscoe'], input_df['island_Biscoe']))
dict_lookup2 = dict(zip(input_df['island_Dream'], input_df['island_Dream']))
dict_lookup3 = dict(zip(input_df['island_Torgersen'], input_df['island_Torgersen']))
dict_lookup4 = dict(zip(input_df['sex_female'], input_df['sex_female']))
dict_lookup4 = dict(zip(input_df['sex_male'], input_df['sex_male']))

In [604]:
n_input_df['island_Biscoe'] = [dict_lookup[item] for item in key_list]
n_input_df['island_Dream'] = [dict_lookup[item] for item in key_list2]
n_input_df['island_Torgersen'] = [dict_lookup[item] for item in key_list3]
n_input_df['sex_female'] = [dict_lookup[item] for item in key_list4]
n_input_df['sex_male'] = [dict_lookup[item] for item in key_list5]

# Mostar dataframe
#n_input_df

In [605]:
# Definir X e Y

X = n_input_df
# Y = output_df

# Reubicar output
pre_output = output_df.copy()

adelie = pre_output.filter(['species_Adelie'], axis = 1)
gentoo = pre_output.filter(['species_Gentoo'], axis = 1)
chinstrap = pre_output.filter(['species_Chinstrap'], axis = 1)
new_output = pd.concat([adelie, gentoo, chinstrap], join = 'outer', axis = 1)

Y = new_output

In [606]:
X

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0         -0.894695       0.779559          -1.424608    -0.567621   
1         -0.821552       0.119404          -1.067867    -0.505525   
2         -0.675264       0.424091          -0.425733    -1.188572   
3         -1.333559       1.084246          -0.568429    -0.940192   
4         -0.858123       1.744400          -0.782474    -0.691811   
..              ...            ...                ...          ...   
328        2.159064       1.338151           0.430446    -0.257145   
329       -0.090112       0.474872           0.073705    -1.002287   
330        1.025333       0.525653          -0.568429    -0.536573   
331        1.244765       0.931902           0.644491    -0.132954   
332        1.135049       0.779559          -0.211688    -0.536573   

     island_Biscoe  island_Dream  island_Torgersen  sex_female  sex_male  
0                0             0                 1           0         1  
1                0             0                 1           1         0  
2                0             0                 1           1         0  
3                0             0                 1           1         0  
4                0             0                 1           0         1  
..             ...           ...               ...         ...       ...  
328              0             1                 0           0         1  
329              0             1                 0           1         0  
330              0             1                 0           0         1  
331              0             1                 0           0         1  
332              0             1                 0           1         0  

[333 rows x 9 columns]

In [607]:
Y

species_Adelie  species_Gentoo  species_Chinstrap
0                 1               0                  0
1                 1               0                  0
2                 1               0                  0
3                 1               0                  0
4                 1               0                  0
..              ...             ...                ...
328               0               0                  1
329               0               0                  1
330               0               0                  1
331               0               0                  1
332               0               0                  1

[333 rows x 3 columns]

### De dataframe a matrices Numpy

In [608]:
inputs = X.to_numpy(dtype='float', copy=True)
expected_output = Y.to_numpy(dtype='float', copy=True)

In [609]:
#epochs
epochs=5000

#factor de aprendizaje
lr = 0.3

#Neuronas de capa entrada a coger // capa oculta //Capa salida
inputNeurons, hiddenNeurons, outputNeurons = 9, 3, 3

#Pesos aleatorios para la capa oculta
hidden_weights = np.random.uniform(size=(inputNeurons, hiddenNeurons))

#Pesos aleatorios para umbral bias de la capa oculta
#(una entrada mas que se le considera a la neurona en la capa oculta)
hidden_bias = np.random.uniform(size=(1, hiddenNeurons))

#Pesos para la capa salida
output_weights = np.random.uniform(size=(hiddenNeurons, outputNeurons))

#Pesos aleatorios para umbral bias de la capa salida
output_bias = np.random.uniform(size=(1, outputNeurons))

In [610]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

def tanh(x):
    t=(np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
    return t
    
def tanh_derivative(x):
    t=(np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))
    dt=1-t**2
    return dt

### Entrenar la red

In [611]:
for _ in range(epochs):
    #Forward Propagation
    hidden_layer_input = np.dot(inputs, hidden_weights)
    hidden_layer_input += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, output_weights)
    output_layer_input += output_bias
    predicted_output = sigmoid(output_layer_input)

    #Backpropagation
    network_error = expected_output - predicted_output
    d_predicted_output = network_error * sigmoid_derivative(predicted_output)
    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    #Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer) * lr

In [612]:
print("Pesos finales: ")
print(hidden_weights)
print("bias finales: ")
print(hidden_bias)
print("Pesos finales capa de salida: ")
print(output_weights)
print("bias finales capa de salida: ")
print(output_bias)

print("\n Predicción : ")
print(predicted_output)

Pesos finales: 
[[ -36154.30070928  -33361.52653343 -101083.2863695 ]
 [ -85185.34628429   -9971.23288022   17293.56215079]
 [  59317.85400371    3656.40587947  -24207.03959335]
 [  72947.22373286   11905.29742765   -2202.83681741]
 [   2330.65302303    3640.14391116   12068.73012866]
 [ -96457.58450472  -22567.61030013  -22384.27836679]
 [ -12375.64027229    4100.17316861   23135.53710151]
 [ -46677.02978069  -10239.1146451    -8379.1390427 ]
 [ -59826.2820415    -4589.751403     21199.32311842]]
bias finales: 
[[-108513.97550665 -108514.10895878 -108514.18544464]]
Pesos finales capa de salida: 
[[-13.42387863  24.90712117 -14.16668504]
 [  3.62708476   0.90727936  -5.22371714]
 [ 21.1991978  -15.44663903 -15.09309096]]
bias finales capa de salida: 
[[-10.15253132 -10.23441364 -10.38788245]]

 Predicción : 
[[1.00000000e+00 2.75148006e-06 3.36094530e-06]
 [1.00000000e+00 2.75148006e-06 3.36094530e-06]
 [9.38493403e-01 9.33593680e-01 9.23422265e-01]
 [1.00000000e+00 2.75148006e-06 3.36

In [613]:
# Aplicando redondeo a resultados de predicción:
rounded_predicted_output = np.around(predicted_output, 2).copy()
rounded_predicted_output

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.94, 0.93, 0.92],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.94, 0.93, 0.92],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.94, 0.93, 0.92],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.94, 0.93, 0.92],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.94, 0.93, 0.92],
       [1.  , 0.  , 0.  ],
       [0.94, 0.93, 0.92],
       [0.94, 0.93, 0.92],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.94, 0.93, 0.92],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.94, 0.93, 0.92],
 

## Red Multicapa de referencia

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

#Entradas 
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
#Salidas reales
expected_output =np.array([[0],[1],[1],[0]])

#epocas
epochs=5000

#factor de aprendizaje
lr=0.25

#Neuronas de capa entrada a coger // capa oculta //Capa salida
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons=2,2,1

#Pesos aleatorios para la capa oculta
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))

#Pesos aleatorios para umbral bias de la capa oculta
#(una entrada mas que se le considera a la neurona en la capa oculta)
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))

#Pesos para la capa salida
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))

#Pesos aleatorios para umbral bias de la capa salida
output_bias = np.random.uniform(size=(1,outputLayerNeurons))

expected_output

for _ in range(epochs):
    #Forward Propagation
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = sigmoid(output_layer_activation)

    #Backpropagation
    error = expected_output - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    #Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer) * lr

print("Pesos finales: ")
print(hidden_weights)
print("bias finales: ")
print(hidden_bias)
print("Pesos finales capa de salida: ")
print(output_weights)
print("bias finales capa de salida: ")
print(output_bias)

print("\n Predicción : ")
print(predicted_output)